# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteTab
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas


[Modulos]
TestTab
Tab
Lista

[BuildInicio]
/OUT:..\produto\TesteTab.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
